### PR TITLE
make Subgraph::add_stmt public

### PR DESCRIPTION
**Pull request by dovahcrow**

### CODE REVIEW

**Comment by besok** [comment]
Thanks for PR

**Comment by raphaelahrens** [comment]
When will this PR be added to a release?

**Comment by besok** [comment]
Is not it presented in "0.9.3" version?
I did bump up the version in the commit after the merge.

**Comment by raphaelahrens** [comment]
No at least when I tried it today. I think this is due to the fact that it is a change in dot-structures.

On crates.io it says last update was 1 year ago.
https://crates.io/crates/dot-structures

**Comment by besok** [comment]
my bad, I did not spot it was a dep. 
Bumped versions for that crate and main one to 0.9.4. 
Should be there.

**Pull request merged**
